plugins/redmine_my_page/config/routes.rb
get '/my/my_custom_form', :to => 'my#my_custom_form', :as => 'myqueryform'
post '/my/update_queries', :to => 'my#update_queries', :as => 'updatemyquery'

plugins/redmine_my_page/app/views/activities/esi.html.erb
<h2><%= @author.nil? ? l(:label_activity) : l(:label_user_activity, link_to_user(@author)).html_safe %><%= " (#{h @filter_title})" if @filter_title %></h2>
<p class="subtitle"><%= l(:label_date_from_to, :start => format_date(@date_to - @days), :end => format_date(@date_to-1)) %></p>

<div id="activity">
<% @events_by_day.keys.sort.reverse.each do |day| %>
<h3><%= format_activity_day(day) %></h3>
<dl>
<% sort_activity_events(@events_by_day[day]).each do |e, in_group| -%>
  <dt class="<%= e.event_type %> <%= "grouped" if in_group %> <%= User.current.logged? && e.respond_to?(:event_author) && User.current == e.event_author ? 'me' : nil %>">
  <%= avatar(e.event_author, :size => "24") if e.respond_to?(:event_author) %>
  <span class="time"><%= format_time(e.event_datetime, false) %></span>
  <%= content_tag('span', h(e.project), :class => 'project') if @project.nil? || @project != e.project %>
  <%= link_to format_activity_title(e.event_title), e.event_url %>
  </dt>
  <dd class="<%= "grouped" if in_group %>"><span class="description"><%= format_activity_description(e.event_description) %></span>
  <span class="author"><%= link_to_user(e.event_author) if e.respond_to?(:event_author) %></span></dd>
<% end -%>
</dl>
<% end -%>
</div>

<%= content_tag('p', l(:label_no_data), :class => 'nodata') if @events_by_day.empty? %>

<div style="float:left;">
<%= link_to_content_update("\xc2\xab " + l(:label_previous),
                   params.merge(:from => @date_to - @days - 1),
                   :title => l(:label_date_from_to, :start => format_date(@date_to - 2*@days), :end => format_date(@date_to - @days - 1)),
                   :accesskey => accesskey(:previous)) %>
</div>
<div style="float:right;">
<%= link_to_content_update(l(:label_next) + " \xc2\xbb",
                   params.merge(:from => @date_to + @days - 1),
                   :title => l(:label_date_from_to, :start => format_date(@date_to), :end => format_date(@date_to + @days - 1)),
                   :accesskey => accesskey(:next)) unless @date_to >= Date.today %>
</div>
&nbsp;
<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => params.merge(:from => nil, :key => User.current.rss_key) %>
<% end %>

<% content_for :header_tags do %>
<%= auto_discovery_link_tag(:atom, params.merge(:format => 'atom', :from => nil, :key => User.current.rss_key)) %>
<% end %>

<% content_for :sidebar do %>
<%= form_tag({}, :method => :get) do %>
<h3><%= l(:label_activity) %></h3>
<ul>
<% @activity.event_types.each do |t| %>
  <li>
    <%= check_box_tag "show_#{t}", 1, @activity.scope.include?(t) %>
    <label for="show_<%=t%>">
      <%= link_to(l("label_#{t.singularize}_plural"),
                  {"show_#{t}" => 1, :user_id => params[:user_id], :from => params[:from]})%>
    </label>
  </li>
<% end %>
</ul>

<% if @project && @project.descendants.active.any? %>
    <p><label><%= check_box_tag 'with_subprojects', 1, @with_subprojects %> <%=l(:label_subproject_plural)%></label></p>
<% else %>
    <%= hidden_field_tag 'with_subprojects', 0, :id => nil %>
<% end %>

<% if @project && @project.users.any? %>
    <p><%= label_tag 'user_id', l(:label_show_user_activity) %><%= select_tag 'user_id', options_for_select( @project.users.sort_by{|n| n.name}.collect{ |u| [u.name, u.id]  }, params[:user_id] ), :include_blank => true, :style => 'margin-left: 10px;width: 75%;' %></p>
  <% else %>
    <p><%= label_tag 'user_id', l(:label_show_user_activity) %><%= select_tag 'user_id', options_for_select( User.active.sort_by{|n| n.name}.collect{ |u| [u.name, u.id]  }, params[:user_id] ), :include_blank => true, :style => 'margin-left: 10px;width: 75%;' %></p>
<% end %>

<p><%= submit_tag l(:button_apply), :class => 'button-small', :name => nil %></p>
<% end %>

<%= render :partial => 'issues/sidebar' %>

<% end %>

<% html_title(l(:label_activity), @author) -%>

plugins/redmine_my_page/app/views/my/_my_custom_form.html.erb
<%= form_tag(updatemyquery_path(:type => formtype), :id => "block-form", :method => :post) do %>
  <%= hidden_field_tag 'object', object %>
  <%= hidden_field_tag 'dashboard_id', dashboard_id %>
  <div class="box tabular">
    <% if formtype == 'my_cust_query' %>
      <p><%= label_tag "custom_limit", l(:label_custom_query_limit)  %>
        <%= text_field_tag "#{formtype}[limit]", custum_query && custum_query[:limit].nil? ? 10 : custum_query[:limit],
          :id => 'custom_limit' %></p>
    <% end %>
    <p><%= label_tag "custom_query_ids", l(:label_custom_queries)  %>
      <%= select_tag     "#{formtype}[query_ids][]", options_for_select(queries,
        custum_query && custum_query[:query_ids].nil? ? "" : custum_query[:query_ids]  ),
         :multiple => formtype == 'my_cust_query' ? true : false, :size => 10,
         :id => 'custom_query_ids', :required => true %></p>
  </div>
  <%= submit_tag l(:button_update) %>
<% end %>

plugins/redmine_my_page/app/views/my/_my_page_activities.html.erb
<% if Setting.plugin_redmine_my_page["my_activity_enable"] == "1" %>
<style type="text/css">
div#spinner
{
  display: none;
  top: 50%;
  left: 50%;
  text-align:center;
  z-index:2;
  overflow: auto;
}
</style>

  <div id="my-activities-<%= "#{query_id}" %>"></div>
  <div id="spinner"><img src="../images/loading.gif" alt="Loading..."/></div>

  <% query = IssueQuery.find_by_id(query_id) %>

  <script type="text/javascript">
    $.ajax({
        url: "<%= query.project_id.nil? ? activity_path(:query_id => query_id) :
                  project_activity_path( :id => query.project_id, :query_id => query_id ) %>",
        cache: false,
        success: function(html){$("#my-activities-"+ "<%= query_id %>").append(html);},
        beforeSend: function(){$('#spinner').fadeIn('fast'); },
        complete: function(){$('#spinner').fadeOut('fast'); }
    });
  </script>

<% else %>
  <h3> <%= l(:label_activity_not_enabled) %></h3>
<% end %>

plugins/redmine_my_page/app/views/my/_my_queries_issue_list.html.erb
<% query = IssueQuery.find_by_id(query_id)
   if !query.nil?

    query_issues_count = query.issue_count
    param_hash = query.project_id.nil? ? { :query_id => query_id } : { :project_id => query.project_id, :query_id => query_id }

    if query_limit.to_i > 0
      sort_array = query.sort_criteria.empty? ? [['id', 'desc']] : query.sort_criteria
      sort_init(sort_array)
      sort_update(query.sortable_columns,"Query-#{query.id}-#{sort_array.flatten.join("")}")
      query.sort_criteria = sort_criteria.to_a
      query_issues = query.issues(:include => [:assigned_to, :tracker, :priority, :category, :fixed_version, :status, :project],
                                :order => sort_clause,
                                :limit => query_limit.to_i)
    %>
    <h3>
      <%= "#{l(:label_query)} : " %><%= link_to "#{query.name}", issues_path( param_hash ) %> (<%= "#{query_issues_count}" %>)
    </h3>
    <%= render :partial => 'issues/list_simple', :locals => { :issues => query_issues } %>
  <% else %>
    <div>
      <%= "#{l(:label_query)} : " %><%= link_to "#{query.name}", issues_path( param_hash ) %> (<%= "#{query_issues_count}" %>)
    </div>
  <% end %>

  <% content_for :header_tags do %>
  <%= auto_discovery_link_tag(:atom,
                              {:controller => 'issues', :action => 'index', :set_filter => 1,
                               :query_id => query_id, :format => 'atom', :key => User.current.rss_key},
                              {:title => l(:label_query) + " : #{query.name}"}) %>
  <% end %>
<% end %>

plugins/redmine_my_page/app/views/my/blocks/_activities.html.erb
<% if Setting.plugin_redmine_my_page["my_activity_enable"] == "1"
  my_activity = user.pref.my_activity %>
  <% if !my_activity.nil? %>
    <div class="contextual">
      <% if my_activity[:query_ids].empty? && controller.action_name == 'page' %>
        <%= link_to l(:label_select_activities), myqueryform_path(:type => 'my_activity'), :remote => true, :class => 'icon icon-add' %>
      <% elsif my_activity[:query_ids].any? %>
        <%= link_to l(:label_update_activities), myqueryform_path(:type => 'my_activity'), :remote => true, :class => 'icon icon-edit' %>
      <% end %>
    </div>
    <% if my_activity[:query_ids].empty? %>
      <h3><%= l(:label_my_activities) %></h3>
    <% end %>
  <% end %>

  <div id='myactivityedit' style='display:none;'></div>
  <div id='myactivities'>
    <% if !my_activity.nil? && my_activity[:query_ids].any? %>
      <% my_activity[:query_ids].each do |queryid| %>
        <%= render :partial => "my/my_page_activities", :locals => { :query_id => queryid,
                :query_limit => my_activity[:limit] } %>
        <hr>
      <% end -%>
    <% end -%>
  </div>
<% else %>
  <h3> <%= l(:label_activity_not_enabled) %></h3>
<% end %>

plugins/redmine_my_page/app/views/my/blocks/_custom_query_issues_list.html.erb
<% dashboard = nil if params[:controller] != 'dashboards'

  my_cust_query = dashboard.nil? ? user.pref.my_cust_query : dashboard.my_cust_query

  if !my_cust_query.nil? %>
  <% if dashboard.nil? || dashboard.manage_layout?(user, "dashboards") %>
    <div class="contextual">
      <% if !my_cust_query[:query_ids].nil? && my_cust_query[:query_ids].empty? && controller.action_name == 'page' %>
        <%= link_to l(:label_select_query),
          myqueryform_path(:type => 'my_cust_query', :object => dashboard ? 'dashboard' : 'user',
          :dashboard_id => dashboard ? dashboard.id : 0), :remote => true, :class => 'icon icon-add' %>
      <% elsif !my_cust_query[:query_ids].nil? && my_cust_query[:query_ids].any? && controller.action_name != 'page_layout' %>
        <%= link_to l(:label_update_query),
        myqueryform_path(:type => 'my_cust_query', :object => dashboard ? 'dashboard' : 'user',
          :dashboard_id => dashboard ? dashboard.id : 0), :remote => true,
        :id => 'update_link_my_cust_query', :class => 'icon icon-edit' %>
      <% end %>
    </div>
  <% end %>
  <% if (!my_cust_query[:query_ids].nil? && my_cust_query[:query_ids].empty?) || controller.action_name == 'page_layout' %>
    <h3><%= l(:label_my_custom_queries) %></h3>
  <% end %>
<% end %>

<% if controller.action_name != 'page_layout' %>
  <div id='myqueryedit' style='display:none;'></div>
  <div id='mycustomquery'>
    <% if !my_cust_query.nil? && !my_cust_query[:query_ids].nil? && my_cust_query[:query_ids].any? %>
      <% my_cust_query[:query_ids].each do |queryid| %>
        <%= render :partial => "my/my_queries_issue_list", :locals => { :query_id => queryid,
                :query_limit => my_cust_query[:limit] } %>
        <hr>
      <% end -%>
    <% end -%>
  </div>
<% end -%>

plugins/redmine_my_page/app/views/my/blocks/_my_custom_queries.html.erb
<% my_queries = IssueQuery.includes(:project).where( :user_id => User.current.id).order("projects.name ASC")
if my_queries && my_queries.any? %>
  <table class="list issues">
    <thead><tr>
      <th>#</th>
      <th><%=l(:field_project)%></th>
      <th><%=l(:label_my_queries)%></th></tr>
    </thead>
    <tbody>
    <% my_queries.each_with_index do |my_query,index|
      next if !my_query.project.nil? && my_query.project.archived?
      param_hash = my_query.project_id.nil? ? { :query_id => my_query.id } : { :project_id => my_query.project_id, :query_id => my_query.id } %>
        <tr id="myquery-<%= index %>" class="<%= cycle('odd', 'even') %>">
          <td class="id"><%= index + 1 %></td>
          <td class="project"><%= my_query.project.nil? ? l(:label_project_all) : link_to_project(my_query.project) %></td>
          <td class="tracker"><%= link_to "#{my_query.name}", issues_path( param_hash ), :target => '_blank' %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

plugins/redmine_my_page/app/views/my/my_custom_form.js.erb
<% if @vartype == 'my_cust_query' %>
  $( '#myqueryedit').html('<%= escape_javascript( render :partial => 'my_custom_form', :locals => { :custum_query => @my_cust_query,
        :queries => @visible_queries, :formtype => @vartype, :object => @object, :dashboard_id => @dashboard && @dashboard.id || 0 }) %>');
  $( '#myqueryedit').show();
  $( '#mycustomquery').hide();
<% else %>
  $( '#myactivityedit').html('<%= escape_javascript( render :partial => 'my_custom_form', :locals => { :custum_query => @my_cust_query,
        :queries => @visible_queries, :formtype => @vartype, :object => @object, :dashboard_id => @dashboard && @dashboard.id || 0 }) %>');
  $( '#myactivityedit').show();
  $( '#myactivities').hide();
<% end -%>
$( '#update_link_my_cust_query').hide();

plugins/redmine_my_page/app/views/settings/_my_page_option_settings.html.erb
<p>
  <label><%= l(:label_my_activity_enable) %></label>
  <%= check_box_tag 'settings[my_activity_enable]', 1, settings.present? && settings[:my_activity_enable] == "1" %>
  <br />
  <em><%= l(:em_my_activity_enable) %></em>
</p>